python ai2holodeck/main.py --query "Arrange a nightstand to the right of a gray wardrobe with drawers and shelves." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Place a kids bed with a drawer and a bed to the left of a grey and wooden modern nightstand." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Put a black nightstand with drawers in front of a double bed. Finnally, put a black and white pendant lamp with a black base above a black and grey double bed." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Put a wardrobe behind a green double bed with pillows and sheets. Then, put a metal wardrobe with compartments to the right of a floral nightstand." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a grey double bed with pillows behind a grey nightstand with a drawer. Next, put a double bed behind a grey nightstand with a drawer." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Put a blue and white double bed with pillows below a gray ceiling lamp with compartments." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Put a green nightstand with a lid right of a green nightstand with a lid. Then, set up a black wooden stool in front of a green nightstand with a lid." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Place a black nightstand with a drawer behind a black spider web shaped ceiling lamp. Next, place a black nightstand with a drawer behind a gray and black double bed." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Set up a wardrobe in front of a nightstand. Additionally, put a grey nightstand with two drawers behind a grey nightstand with two drawers." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Arrange a green and gray double bed in front of a nightstand." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Place a black and grey double bed with pillows below a black and white pendant lamp with a black base. Additionally, install a black and white pendant lamp with a black base right of a wardrobe." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Add a wardrobe right of a pendant lamp." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Arrange a wardrobe right of a black tv stand with drawers." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Set up a double bed right of a wardrobe. Then, add a nightstand left of a grey double bed with headboard and pillows." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Arrange a nightstand in front of a nightstand. And position a blue single bed left of a grey tv stand." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a chair left of a black and silver ceiling lamp with a design." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Place a brown and black double bed with a comforter below a silver circular ceiling lamp. Finnally, set up a brown and black double bed with a comforter behind a wardrobe." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Put a double bed below a black pendant lamp with glass bottles. And add a double bed behind a grey wardrobe with a door and a drawer." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a grey tv stand with a wooden shelf in front of a wardrobe with a door and drawers. Set up a gray double bed with sheets and pillows to the left of a marble console table with holes." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Set up a wooden wardrobe with a drawer and two shelves behind a yellow and white double bed. Finnally, add a wardrobe behind a yellow and white double bed." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a metal pendant lamp with three circles to the right of a brown and beige dining chair." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Place a wooden coffee table behind a black and white multi-seat sofa with pillows." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Hang a pendant lamp in front of a beige console table. Next, set up a black dining chair with a bar stool closely in front of a metal pendant lamp." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Set up a black pendant lamp with dots above a black and wooden dining table. Additionally, place a beige loveseat sofa in front of a black and gold chandelier with black beads." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Add a dining chair closely to the left of a brown and beige dining chair." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Arrange a brown dining table with a wooden top behind a multi seat sofa. Put a multi-seat sofa with pillows to the right of a wooden tv stand with drawers." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Arrange a black leather multi-seat sofa with pillows left of a tv stand with shelves." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a black multi-seat sofa with pillows to the left of a black and gray pendant lamp with a black shade. Next, arrange a black plastic dining table in front of a black and gray pendant lamp with a black shade." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Arrange a dining chair in front of a grey dining table with legs. And place a console table behind a dining chair." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Add a black rectangular dining table with legs closely behind a brown and beige dining chair." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a white dining table with a cross base in front of a black and brown tv stand with drawers. Then, put a white dining table with a cross base closely in front of a gray dining chair with black legs." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a brown and beige dining chair closely in front of a black rectangular dining table with legs. Finnally, place a brown and beige dining chair to the near left of a metal and glass pendant lamp." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Put a wooden dining table with a wooden top and legs closely in front of a black leather lounge chair with wooden seat. Finnally, arrange a wooden console table with glass doors in front of a modern pendant lamp with metal rods." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Put a black rectangular dining table with legs closely behind a dining chair." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a coffee table with a vase and flowers in front of a floral dining chair." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Put a coffee table with a book and a pencil left of a multi-seat sofa with pillows. Finnally, add a lounge chair to the right of a black and white tv stand with drawers." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Place a black and white geometric tv stand left of a black and grey cushioned lounge chair." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a blue and white console table with blue top right of a blue dining table with a wooden top. Finnally, place a blue dining table with a wooden top behind a white cabinet with a vase." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Set up a multi-seat sofa with pillows and a blanket right of a brown ceiling lamp with a black handle. Put a pendant lamp to the left of a multi-seat sofa with pillows and a blanket." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Hang a black pendant lamp hanging in front of a black cabinet with drawers." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Add a checkered dining chair left of a blue loveseat sofa with pillows." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Place a black and gold corner side table with a shelf left of a dining table. Arrange a dining table left of a black and gold corner side table with a shelf." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Add a metal pendant lamp with bars in front of a brown dining table. And add a brown dining table closely behind a gray armchair with a metal frame." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Put a wine cabinet left of a ceiling lamp." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Set up a black dining table with metal plates in front of a black tv stand with shelves and drawers." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Add a black dining chair with seat and back left of a pendant lamp. Set up a black circular ceiling lamp to the near left of a black and white pendant lamp with a design." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Place a dining table to the left of a black triangle coffee table with two legs. Additionally, arrange a black triangle coffee table with two legs right of a grey dining table with a wooden base." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a black and white dining chair with a white cushion in front of a black coffee table with a blue stripe. Place a black coffee table with a blue stripe behind a black and white dining chair with a white cushion." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Set up a black glass corner side table with a circular base left of a black and white circular pendant lamp." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Place a black bookshelf with shelves left of a blue and brown dining table with a runner." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Arrange a gray multi-seat sofa with pillows left of a coffee table. Add a gray tv stand with doors right of a pendant lamp." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a black and white coffee table with a black cover right of an l shaped sofa." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Arrange a lounge armchair to the left of a black and white tv stand with drawers. Then, set up a corner side table in front of a multi seat sofa." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Arrange a dining table closely in front of a dining chair. Additionally, put a multi seat sofa behind a white dining chair with a black frame." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Arrange a multi-seat sofa with pillows left of a set of three nesting corner side tables." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Position a multi-seat sofa with a hole behind a wooden corner side table with a pine cone on top." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Put a black multi-seat sofa with black pillows in front of a coffee table." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Arrange a coffee table in front of a multi-seat sofa with pillows." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Place a grey and black multi-seat sofa right of a gray dining chair with black legs." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
python ai2holodeck/main.py --query "Add a black oval dining table with a black base in front of a multi seat sofa." --openai_api_key $CA_API_KEY3 --openai_api_base https://api.chatanywhere.tech/v1 --model_name gemini-2.5-pro-preview-06-05 --save_dir ./data/scenes_mr3
